api_key_env: CROWDIN_KEY
project_identifier: transferwise-send-money-pages-og-images
base_path: .
preserve_hierarchy: false
files:
  - source: /translations/en.json
    translation: /translations/%locale%.%file_extension%
